version: '2'

networks:
  private:
    driver: bridge
services: 
  hub:
    image: selenium/hub
    ports:
      - 4444:4444
    networks:
      - private
    environment:
    - TZ=Asia/Yekaterinburg
  ff-chrome:
    image: pilshchikov/docker-node-ff-chrome
    networks:
      - private
    depends_on:
      - hub
    environment:
      - TZ=Asia/Yekaterinburg
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
      - NODE_MAX_INSTANCES=10
      - NODE_MAX_SESSION=10
    
    