#!/bin/bash

CHROME_VERSION=$( sudo dpkg -s google-chrome-stable | grep Version | cut -d " " -f 2 | cut -d "-" -f 1 )
FIREFOX_VERSION=$( firefox -version | cut -d " " -f 3 )

echo "
{
  \"capabilities\": [

    {
      \"version\": \"$FIREFOX_VERSION\",
      \"browserName\": \"firefox\",
      \"maxInstances\": $NODE_FIREFOX_MAX_INSTANCES,
      \"seleniumProtocol\": \"WebDriver\"
    },
    {
      \"version\": \"$CHROME_VERSION\",
      \"browserName\": \"chrome\",
      \"maxInstances\": $NODE_CHROME_MAX_INSTANCES,
      \"seleniumProtocol\": \"WebDriver\"
    }
  ],
  \"proxy\": \"org.openqa.grid.selenium.proxy.DefaultRemoteProxy\",
  \"maxSession\": $NODE_MAX_SESSION,
  \"port\": $NODE_PORT,
  \"register\": true,
  \"registerCycle\": $NODE_REGISTER_CYCLE
}" 
